[package]
name = "xc-sync"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
idna = "1"
idna_adapter = { version = "1.2", features = ["compiled_data"] }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
xc-core.workspace = true

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
