[package]
name = "xc-sync"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
idna = "1"
idna_adapter = { version = "1.2", features = ["compiled_data"] }
regex = "1"
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
url = "2"
xc-core.workspace = true
xc-engine.workspace = true
yaml-rust2 = "0.10"

[dev-dependencies]
serde_json = { workspace = true, features = ["float_roundtrip"] }
tempfile = "3"
tokio.workspace = true

[lints]
workspace = true
